### ISSUE TITLE
Issue 32: Write a README.md according to requirements

### ISSUE THREAD

**Issue by VinterSallad** [Emiesce/dd2480-assignment1#49]

**Comment by VinterSallad** [comment]
Statement of Contribution:

Alexander: Implemented CMV8, 10, 12 and 14 along with their tests, Reviewed CMV 7, 9, 11 and 13. Refactored the base code to allow for easier testing and since using static keyword is not the normal Java convention. Setup and researched how to use JUnit for Unit testing to pave the way for the tests.

**Comment by MercuriaL01** [comment]
Statement of Contribution: Implemented CMV7, 9, 11, 13 along with their tests. Reviewed CMV8, 12, 14. Also created the helper function angleBetweenPoints and a test for it.

**Comment by roxannecvl** [comment]
Roxanne :  Implemented CMV0-6 along with their tests, Reviewed CMV PUMCreator, FUVCreator, Decide() and PUMCreator(). Created helper function smallestRadius and distance which respectively give the radius of the smallest circle containing three given points and calculate the distance between two points.
